# Generated by Django 3.0 on 2019-12-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Unique_Squirrel_ID', models.CharField(help_text='Unique Squirrel', max_length=64)),
                ('Hectare', models.CharField(help_text='Hectare', max_length=16)),
                ('Shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], help_text='AM or PM', max_length=8)),
                ('Date', models.CharField(help_text='Date', max_length=16)),
                ('Hectare_Squirrel_Number', models.IntegerField()),
                ('Age', models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('', '')], help_text='Adult or Juvenile', max_length=16)),
                ('Primary_Fur_Color', models.CharField(choices=[('Black', 'Black'), ('Cinnamon', 'Cinnamon'), ('Gray', 'Gray'), ('', '')], help_text='Primary Fur Color', max_length=32)),
                ('Highlight_Fur_Color', models.CharField(help_text='Highlight Fur Color', max_length=64)),
                ('Combination_of_Primary_and_Highlight_Color', models.CharField(help_text='Combination of Primary and Highlight Color', max_length=64)),
                ('Color_notes', models.CharField(help_text='Color notes', max_length=64)),
                ('Location', models.CharField(choices=[('Above Ground', 'Abve Ground'), ('Ground PLane', 'Ground PLane'), ('', '')], help_text='Location', max_length=64)),
                ('Above_Ground_Sighter_Measurement', models.CharField(help_text='Above Ground Sighter Measurement', max_length=32)),
                ('Specific_Location', models.CharField(help_text='Specific Location', max_length=128)),
                ('Running', models.BooleanField()),
                ('Chasing', models.BooleanField()),
                ('Climbing', models.BooleanField()),
                ('Eating', models.BooleanField()),
                ('Foraging', models.BooleanField()),
                ('Other_Activities', models.CharField(help_text='Other Activities', max_length=128)),
                ('Kuks', models.BooleanField()),
                ('Quaas', models.BooleanField()),
                ('Moans', models.BooleanField()),
                ('Tail_flags', models.BooleanField()),
                ('Tail_twitches', models.BooleanField()),
                ('Approaches', models.BooleanField()),
                ('Indifferent', models.BooleanField()),
                ('Runs_from', models.BooleanField()),
                ('Other_Interactions', models.CharField(help_text='Other Interactions', max_length=256)),
                ('Lat_Long', models.CharField(help_text='Lat/Long', max_length=256)),
                ('Zip_Codes', models.CharField(blank=True, max_length=16)),
                ('Community_Districts', models.CharField(blank=True, max_length=16)),
                ('Borough_Boundaries', models.CharField(blank=True, max_length=16)),
                ('City_Council_Districts', models.CharField(blank=True, max_length=16)),
                ('Police_Precincts', models.CharField(blank=True, max_length=16)),
            ],
        ),
    ]
